# Generated by Django 4.2.2 on 2023-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_contact_account_type_contact_address_contact_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6),
        ),
    ]
