# Generated by Django 4.2.2 on 2023-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_customer_material_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='materials_provide',
            field=models.ManyToManyField(blank=True, to='userapp.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
