# Generated by Django 4.2.2 on 2023-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_city_country_person_delete_accounttype_delete_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('debit_card', models.BooleanField(default=False)),
                ('credit_card', models.BooleanField(default=False)),
                ('cheque_book', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
