# Generated by Django 4.2.2 on 2023-10-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_person_address_person_age_person_dob_person_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
