# Generated by Django 4.2.2 on 2023-10-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_rename_city_person_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
    ]
