# Generated by Django 4.2.2 on 2023-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_rename_city_branch_rename_country_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Checking', 'Checking Account'), ('Investment', 'Investment Account')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='materials_provide',
            field=models.BooleanField(default=False),
        ),
    ]
